name             "wordpress"
maintainer       "booncon PIXELS"
maintainer_email "hello@pixels.fi"
license          "All rights reserved"
description      "Deploy WordPress from Github"
long_description "Deploy WordPress from Github"
version          "0.8.0"
